---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "bundle_coloring"
channels:
  - Docker
  - Apptainer
dependencies:
  - "scilpy"
