name: Lint nf-scil component

on:
  workflow_dispatch:
    inputs:
      component:
        description: "A tag describing the component"
        required: true
        type: string
      type:
        description: "Type of component"
        required: true
        type: choice
        options:
          - module
          - subworkflow
      nextflow_version:
        description: "Nextflow version to use"
        required: false
        type: string
        default: "24.04.4"
  workflow_call:
    inputs:
      component:
        description: "A tag describing the component"
        required: true
        type: string
      type:
        description: "Type of component"
        required: true
        type: string
      nextflow_version:
        description: "Nextflow version to use"
        required: false
        type: string
        default: "24.04.4"

run-name: Lint ${{ inputs.component }}
jobs:
  nf-core-lint:
    runs-on: ubuntu-latest
    name: lint - ${{ inputs.component }}

    steps:
      - uses: actions/checkout@v4
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.*"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'poetry'
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: nf-core/setup-nextflow@v2
        with:
          version: ${{ inputs.nextflow_version }}

      - name: Install nf-core tools
        run: |
          poetry install --no-root

      - name: Lint ${{ inputs.type }} ${{ inputs.component }}
        env:
          GIT_CLONE_PROTECTION_ACTIVE: false
        run: |
          poetry run nf-core --verbose ${{ inputs.type }}s \
            --git-remote https://github.com/${{ github.repository }}.git \
            lint ${{ inputs.component }}
