name: Test nf-scil module

on:
  workflow_dispatch:
    inputs:
      paths:
        description: "Paths nf-test should look into for tests"
        required: true
        type: string
      profile:
        description: "Which profile to use to run the module's tests"
        default: 'docker'
        type: choice
        options:
          - docker
          - singularity
      runner:
        description: "Runner label to use for the test run"
        default: 'ubuntu-latest'
        type: string
      nextflow_version:
        description: "Nextflow version to use"
        required: false
        type: string
        default: "24.04.4"
      nf_test_version:
        description: "nf-test version to use"
        required: false
        type: string
        default: "0.9.0-rc1"
  workflow_call:
    inputs:
      profile:
        description: |
          Which profile to use to run the module's tests, either :
            - docker
            - singularity
        default: 'docker'
        type: string
      paths:
        description: "Paths nf-test should look into for tests"
        required: true
        type: string
      runner:
        description: "Runner label to use for the test run"
        default: 'ubuntu-latest'
        type: string
      nextflow_version:
        description: "Nextflow version to use"
        required: false
        type: string
        default: "24.04.4"
      nf_test_version:
        description: "nf-test version to use"
        required: false
        type: string
        default: "0.9.0-rc1"

env:
  NXF_SINGULARITY_CACHEDIR: /home/runner/.singularity_cache/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity

run-name: Run nf-test on ${{ inputs.paths }}
jobs:
  nf-test:
    runs-on: ${{ inputs.runner }}
    name: test - ${{ inputs.paths || 'skipped' }}
    if: inputs.paths != '' && inputs.profile != ''
    env:
      NXF_ANSI_LOG: false
      NXF_DISABLE_CHECK_LATEST: true
      NFTEST_VERSION: "${{ inputs.nf_test_version }}"
      # nf-test directories need to be placed on an ephemeral disk accessible to docker.
      # In our case, it's only the _work workspace for security reasons
      NXF_WORKDIR: /home/runner/_work
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: nf-core/setup-nextflow@v2
        with:
          version: ${{ inputs.nextflow_version }}
      - name: Setup nf-test
        uses: AlexVCaron/setup-nf-test@2c5a31b90b34d97abf155b57ee0f79c7f5aa118a
        # Used to make the action executable on our runners. Related to how the home
        # and work directories are set up from ephemeral disks. See nf-core/setup-nf-test/issues/6
        with:
          version: ${{ inputs.nf_test_version }}

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pdiff cryptography

      - name: Fix nf-test launching jvm with too much memory
        run: |
          sed -i 's/-Xmx10g//' $(which nf-test)

      - name: Compute test run UID
        uses: actions/github-script@v7
        id: test-run-identifier
        with:
          script: |
            identifier='${{ inputs.paths }}'.toLowerCase().replaceAll(/[/. ]+/g, '-').trim('-');
            core.setOutput('uid', identifier);

      - name: Cache test archives under test UID
        uses: actions/cache@v4
        with:
          path: ${{ env.NXF_WORKDIR }}/nf-scil-test-archives
          key: |
            nf-scil-test-data-cache-${{ steps.test-run-identifier.outputs.uid }}
            nf-scil-test-data-cache-

      - name: Run nf-test
        env:
          NFT_DIFF: "pdiff"
          NFT_DIFF_ARGS: "--line-numbers --width 120 --expand-tabs=2"
          TMPDIR: ${{ env.NXF_WORKDIR }}/tmpdir
          NFT_WORKDIR: ${{ env.NXF_WORKDIR }}/.nf-test
          NXF_CACHE_DIR: ${{ env.NXF_WORKDIR }}/.nextflow
          NXF_TEMP: ${{ env.NXF_WORKDIR }}/tmpdir
          NFSCIL_TEST_DATA_HOME: ${{ env.NXF_WORKDIR }}
        run: |
          # use "docker_self_hosted" if it runs on self-hosted runner and inputs.profile=docker
          if [ "${{ inputs.profile }}" == "docker" ]; then
            PROFILE="docker_self_hosted"
          else
            PROFILE=${{ inputs.profile }}
          fi

          mkdir -p ${{ env.TMPDIR }}
          nf-test test \
            --profile=$PROFILE \
            --tap=test.tap \
            --verbose \
            --debug \
            ${{ inputs.paths }}

      - uses: pcolby/tap-summary@v1
        with:
          path: >-
            test.tap

      - name: Tests logs
        if: failure()
        run: |
          shopt -s globstar
          for f in ${{ env.NXF_WORKDIR }}/.nf-test/tests/**/work/**/.command.log
          do

          echo "$(sed '3q;d' $(dirname $f)/.command.run)"
          cat $f

          done

      - name: Collect test reports
        if: always()
        run: |
          mkdir -p tests_reports
          i=1
          for t in ${{ env.NXF_WORKDIR }}/.nf-test/tests/*
          do
            tag=$(cat $t/meta/mock.nf | grep -E 'include \{.*' | tail -1 | cut -d' ' -f3)_$i
            cp $t/report.html tests_reports/${tag}.html
            i=$((i+1))
          done

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ steps.test-run-identifier.outputs.uid }}
          path: tests_reports/
          overwrite: true
          retention-days: 1
          compression-level: 9

      - name: Collect test working directories
        if: failure()
        run: |
          mkdir -p tests_workdir
          for t in ${{ env.NXF_WORKDIR }}/.nf-test/tests/**/work/**/.command.log
          do
            tag=$(sed -n '3p' $(dirname $t)/.command.run | cut -d' ' -f3 | tr -d "'")
            cp -R $(dirname $t) tests_workdir/$tag
          done

      - name: Upload test working directories
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: tests-workdir-${{ steps.test-run-identifier.outputs.uid }}
          path: tests_workdir/
          overwrite: true
          retention-days: 1
          compression-level: 9
          include-hidden-files: true

      - name: Clean up
        if: always()
        run: |
          sudo rm -rf ${{ env.NXF_WORKDIR }}/.nf-test
